Repository ProjectEKA/consent-manager, pull requests merged in 2020-01, with the labels that each got.

#7 [EKA-0000] Integrate with sonar cloud
  .github/workflows/ci.yml
  .github/workflows/feature-branches.yml
  build.gradle
  docker-compose.development.yml
  docker-compose.yml
Labels: enhancement

#4 [EKA-35] contract for grant consent request.
  .github/workflows/ci.yml
  src/main/resources/static/api.yaml
Labels: api-contract

#54 EKA-29 | updating consent requests list for HIType def
  src/main/resources/static/api.yaml
Labels: question
